### ISSUE TITLE
White Screen of Death

### ISSUE THREAD

**Issue by Leftspace21** [ypranay/org.civicrm.civirebux#3]
Installing Rebux went without a glitch - however, on clicking Rebux under Reports get white screen of death. 

Got the following message in the Apache error log:
AH01071: Got error 'PHP message: PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4104 bytes) in MYDOMAIN/administrator/components/com_civicrm/civicrm/CRM/Core/DAO.php on line 1372\n', referer: MYDOMAIN/administrator/index.php?option=com_civicrm

So it looks like it hit the PHP memory_limit of 128MB.
I upped the memory_limit to 256MB (the highest I can go to) and then got the message:
AH01071: Got error 'PHP message: PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 65552 bytes) in MYDOMAIN/administrator/components/com_civicrm/civicrm/CRM/Core/DAO.php on line 1372\n', referer: MYDOMAIN/administrator/index.php?option=com_civicrm

**Comment by ypranay** [comment]
Looks like it's not because of CiviREBUX, but due to some server memory issues. Here are a few quick suggestions which you can try:
-  In your "wp-config.php", add this line `define( ‘WP_MEMORY_LIMIT’, ‘600M’ );` 
-  Since, you already tried to increase the PHP Memory Limit and it still fails, please get in touch with your host provider, because sometimes even updating the PHP Memory Limit will not cause any change because the limit is overridden from the host provider's end. Also, ask them to look at it from their end or suggest you another hosting plan, if required. 

CiviREBUX worked well for a lot of other users, so I guess the solution should come from either of the two above. Let me know if both don't work out.
